-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 516cc9fa72ad09699f2c03ffbd0aa7f60d75b59a
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
        args:
        - -i
        - --ignore=E265,E309,E501
        - -v
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
    -   id: pretty-format-json
    -   id: check-merge-conflict
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: debug-statements
    -   id: detect-private-key
    -   id: double-quote-string-fixer
    -   id: requirements-txt-fixer
    -   id: name-tests-test
    -   id: flake8
        args:
        - --max-line-length=100
        - --max-complexity=10
-   repo: git://github.com/asottile/reorder_python_imports
    sha: 3d86483455ab5bd06cc1069fdd5ac57be5463f10
    hooks:
    -   id: reorder-python-imports
-   repo: git://github.com/guykisel/pre-commit-robotframework-tidy
    sha: 07d9ed1dea81d8c0abc783a8f3469ca01801004b
    hooks:
    -   id: robotframework-tidy-wrapper
-   repo: git://github.com/guykisel/prospector-mirror
    sha: 00fbd80101566b1b9c873c71f2ab7b95b8bd0a7d
    hooks:
    -   id: prospector
